import { NextResponse } from 'next/server'
import { headers } from 'next/headers'
import { and, eq } from 'drizzle-orm'
import { auth } from '@/lib/auth'
import { db } from '@/lib/db'
import { activities, activityCompletions, savedActivities } from '@/lib/db/schema'
async function userId() { const session = await auth.api.getSession({ headers: await headers() }); return session?.user?.id }
export async function GET() { const id = await userId(); if (!id) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); const seed = [{ id: 'reset-your-nervous-system', title: 'Reset your nervous system', category: 'Breathe', description: 'A 4-minute breathing practice', instructions: 'Breathe slowly and gently.', estDuration: 4 }, { id: 'put-it-into-words', title: 'Put it into words', category: 'Reflect', description: 'A guided reflection for today', instructions: 'Write whatever feels true.', estDuration: 8 }, { id: 'a-softer-start', title: 'A softer start', category: 'Breathe', description: 'A three-minute morning grounding practice.', instructions: 'Notice five things around you.', estDuration: 3 }, { id: 'name-what-is-here', title: 'Name what is here', category: 'Reflect', description: 'A gentle prompt for meeting your feelings.', instructions: 'Name the feeling without judging it.', estDuration: 8 }, { id: 'let-your-body-lead', title: 'Let your body lead', category: 'Move', description: 'Small movements to come back to yourself.', instructions: 'Stretch in a way that feels comfortable.', estDuration: 6 }, { id: 'the-pause-practice', title: 'The pause practice', category: 'Rest', description: 'A quiet reset for a busy afternoon.', instructions: 'Take three quiet minutes.', estDuration: 5 }]; for (const item of seed) await db.insert(activities).values(item).onConflictDoNothing(); const [items, saved, completed] = await Promise.all([db.select().from(activities), db.select().from(savedActivities).where(eq(savedActivities.userId, id)), db.select().from(activityCompletions).where(eq(activityCompletions.userId, id))]); return NextResponse.json({ items, saved: saved.map((x) => x.activityId), completed: completed.map((x) => x.activityId) }) }
export async function POST(request: Request) { const id = await userId(); if (!id) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); const body = await request.json(); if (typeof body.activityId !== 'string' || !['save', 'unsave', 'complete'].includes(body.action)) return NextResponse.json({ error: 'Invalid request' }, { status: 400 }); if (body.action === 'save') await db.insert(savedActivities).values({ userId: id, activityId: body.activityId }).onConflictDoNothing(); if (body.action === 'unsave') await db.delete(savedActivities).where(and(eq(savedActivities.userId, id), eq(savedActivities.activityId, body.activityId))); if (body.action === 'complete') await db.insert(activityCompletions).values({ id: crypto.randomUUID(), userId: id, activityId: body.activityId }); return NextResponse.json({ ok: true }) }
