'use client'

import { useEffect, useState } from 'react'
import { useChat } from '@ai-sdk/react'
import { ArrowUpRight, BookOpen, Home, MessageCircle, Search, Sparkles, UserRound } from 'lucide-react'
import { authClient, useSession } from '@/lib/auth-client'
import type { View } from '@/components/dashboard/dashboard-types'
import { DashboardSidebar } from '@/components/dashboard/dashboard-sidebar'
import { WardOrb } from '@/components/dashboard/ward-orb'

const moods = ['Low', 'Okay', 'Good', 'Great']

function Today({ name, mood, onMood }: { name: string; mood: string | null; onMood: (value: string) => void }) {
  return <div className="page-view"><div className="welcome-row"><div><p className="eyebrow">A soft place to land</p><h1>Good morning, {name}<span className="sun-dot">.</span></h1><p className="intro">You don&apos;t have to have it all figured out. Just be here for this moment.</p></div></div><section className="surface mood-card"><div className="section-kicker">DAILY CHECK-IN</div><h2>How are you arriving today?</h2><p>A tiny check-in is a powerful way to notice yourself.</p><div className="mood-options">{moods.map((item) => <button className={`mood-option ${mood === item ? 'mood-selected' : ''}`} key={item} onClick={() => onMood(item)} aria-pressed={mood === item}><span>{item === 'Low' ? '◌' : item === 'Okay' ? '◐' : item === 'Good' ? '◒' : '✦'}</span><small>{item}</small></button>)}</div></section><section className="ward-hero"><div><span className="hero-label">A MOMENT WITH WARD</span><h2>What feels most present for you?</h2><p>You can say as much or as little as you like.</p></div><WardOrb small /></section></div>
}

function Support({ onChat }: { onChat: () => void }) { return <div className="page-view"><div className="page-heading"><p className="eyebrow">You do not have to do this alone</p><h1>Support<span className="sun-dot">.</span></h1><p className="intro">A few ways to find steadiness, right when you need it.</p></div><section className="support-grid"><section className="ward-support"><WardOrb small /><div><span className="hero-label">YOUR COMPANION</span><h2>Talk it through with Ward.</h2><p>A listening space for the things that feel hard to carry.</p><button className="primary-button" onClick={onChat}><MessageCircle aria-hidden="true" /> Open Ward</button></div></section><section className="crisis-card"><h2>You deserve immediate support.</h2><p>In the U.S., call or text 988. If you are in immediate danger, contact emergency services.</p><a className="outline-button" href="https://988lifeline.org/" target="_blank" rel="noreferrer">View crisis resources <ArrowUpRight aria-hidden="true" /></a></section></section></div> }

function Profile({ name, onSave }: { name: string; onSave: (value: string) => void }) { const [value, setValue] = useState(name); const [password, setPassword] = useState(''); const [newPassword, setNewPassword] = useState(''); const [message, setMessage] = useState(''); return <div className="page-view"><div className="page-heading"><p className="eyebrow">A space that feels like yours</p><h1>Your profile<span className="sun-dot">.</span></h1></div><section className="profile-layout"><div className="profile-card"><div className="large-avatar">{value.charAt(0).toUpperCase()}</div><input className="profile-name-input" value={value} onChange={(event) => setValue(event.target.value)} onBlur={() => onSave(value)} aria-label="Your name" /><p>Growing daily</p></div><div className="surface account-security"><span className="section-kicker">ACCOUNT SECURITY</span><h3>Change password</h3><form className="auth-form" onSubmit={async (event) => { event.preventDefault(); try { await authClient.changePassword({ currentPassword: password, newPassword, revokeOtherSessions: false }); setMessage('Password updated successfully.'); setPassword(''); setNewPassword('') } catch { setMessage('We could not update your password.') } }}><input type="password" placeholder="Current password" value={password} onChange={(event) => setPassword(event.target.value)} required /><input type="password" placeholder="New password" value={newPassword} onChange={(event) => setNewPassword(event.target.value)} minLength={8} required /><button className="outline-button" type="submit">Update password</button></form>{message && <p className="form-status">{message}</p>}</div></section></div> }

function Insights() { const [data, setData] = useState<any>(null); useEffect(() => { fetch('/api/insights').then((response) => response.json()).then(setData).catch(() => setData({ moods: [], counts: {} })) }, []); return <div className="page-view"><div className="page-heading"><p className="eyebrow">A gentle look back</p><h1>Your insights<span className="sun-dot">.</span></h1><p className="intro">Notice patterns without needing to judge them.</p></div><div className="insights-grid"><section className="surface rhythm-card"><span className="section-kicker">LAST 7 DAYS</span><h2>Your mood rhythm</h2><div className="week-graph">{(data?.moods || []).slice().reverse().map((item: any) => <div className="week-bar" key={item.id}><span style={{ height: '60%' }} title={item.mood} /><small>{new Date(item.createdAt).toLocaleDateString(undefined, { weekday: 'short' })}</small></div>)}</div></section><section className="surface entry-list"><span className="section-kicker">WARD&apos;S REFLECTION</span><p className="insight-summary">{data?.summary || 'Keep noticing what supports you.'}</p></section></div></div> }

export default function Page() { const { data: session, isPending } = useSession(); const [active, setActive] = useState<View>('Today'); const [mood, setMood] = useState<string | null>(null); const [profileName, setProfileName] = useState('friend'); const [showChat, setShowChat] = useState(false); const [input, setInput] = useState(''); const chat = useChat(); const name = session?.user?.name || session?.user?.email?.split('@')[0] || profileName; useEffect(() => { if (session?.user) fetch('/api/profile').then((response) => response.json()).then((profile) => setProfileName(profile.displayName || name)) }, [session?.user, name]); if (isPending) return <main className="auth-page" />; if (!session?.user) { window.location.replace('/sign-in'); return null } const content = active === 'Today' ? <Today name={name} mood={mood} onMood={(value) => { setMood(value); void fetch('/api/mood', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ mood: value }) }) }} /> : active === 'Insights' ? <Insights /> : active === 'Support' ? <Support onChat={() => setShowChat(true)} /> : active === 'Profile' ? <Profile name={name} onSave={(value) => { setProfileName(value); void fetch('/api/profile', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ displayName: value }) }) }} /> : <div className="page-view"><div className="page-heading"><p className="eyebrow">A little space to explore</p><h1>{active}<span className="sun-dot">.</span></h1><p className="intro">Small practices for the moments in between.</p></div></div>; return <div className="app-shell"><DashboardSidebar active={active} onChange={setActive} name={name} /><main className="main-content">{content}</main>{showChat && <section className="chat-panel"><div className="chat-header"><div><strong>Ward</strong><span>Here with you</span></div><button className="icon-button" onClick={() => setShowChat(false)} aria-label="Close chat">×</button></div><div className="chat-messages">{chat.messages.map((message) => <div className={`chat-message ${message.role === 'user' ? 'user-message' : 'ward-message'}`} key={message.id}>{message.parts?.filter((part: any) => part.type === 'text').map((part: any) => part.text).join('')}</div>)}</div><form className="chat-composer" onSubmit={(event) => { event.preventDefault(); if (input.trim()) { void chat.sendMessage({ text: input }); setInput('') } }}><input value={input} onChange={(event) => setInput(event.target.value)} placeholder="Write what&apos;s on your mind..." aria-label="Message Ward" /><button type="submit" aria-label="Send message"><ArrowUpRight aria-hidden="true" /></button></form></section>}</div> }
