import { NextResponse } from 'next/server'
import { headers } from 'next/headers'
import { eq } from 'drizzle-orm'
import { auth } from '@/lib/auth'
import { db } from '@/lib/db'
import { wellnessProfile } from '@/lib/db/schema'
async function getUser() { const session = await auth.api.getSession({ headers: await headers() }); return session?.user }
export async function GET() { const user = await getUser(); if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); const [profile] = await db.select().from(wellnessProfile).where(eq(wellnessProfile.userId, user.id)).limit(1); return NextResponse.json(profile ?? { userId: user.id, displayName: user.name, streak: 0, notificationsEnabled: true, gentleModeEnabled: false, hasOnboarded: false, primaryFocus: 'feeling steady', reminderTime: null, morningReminder: true, middayReminder: true, eveningReminder: true, weeklyInsightsEnabled: true, hasSeenSafetyNotice: false }) }
export async function PATCH(request: Request) { const user = await getUser(); if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); const body = await request.json(); const [existing] = await db.select().from(wellnessProfile).where(eq(wellnessProfile.userId, user.id)).limit(1); const base = existing ?? { displayName: user.name, notificationsEnabled: true, gentleModeEnabled: false, hasOnboarded: false, primaryFocus: 'feeling steady', reminderTime: null, morningReminder: true, middayReminder: true, eveningReminder: true, weeklyInsightsEnabled: true, hasSeenSafetyNotice: false }; const values = { displayName: typeof body.displayName === 'string' ? body.displayName.trim().slice(0, 80) || base.displayName : base.displayName, notificationsEnabled: typeof body.notificationsEnabled === 'boolean' ? body.notificationsEnabled : base.notificationsEnabled, gentleModeEnabled: typeof body.gentleModeEnabled === 'boolean' ? body.gentleModeEnabled : base.gentleModeEnabled, hasOnboarded: typeof body.hasOnboarded === 'boolean' ? body.hasOnboarded : base.hasOnboarded, primaryFocus: typeof body.primaryFocus === 'string' ? body.primaryFocus.trim().slice(0, 120) || base.primaryFocus : base.primaryFocus, reminderTime: typeof body.reminderTime === 'string' ? body.reminderTime.trim().slice(0, 20) || null : base.reminderTime, morningReminder: typeof body.morningReminder === 'boolean' ? body.morningReminder : base.morningReminder, middayReminder: typeof body.middayReminder === 'boolean' ? body.middayReminder : base.middayReminder, eveningReminder: typeof body.eveningReminder === 'boolean' ? body.eveningReminder : base.eveningReminder, weeklyInsightsEnabled: typeof body.weeklyInsightsEnabled === 'boolean' ? body.weeklyInsightsEnabled : base.weeklyInsightsEnabled, hasSeenSafetyNotice: typeof body.hasSeenSafetyNotice === 'boolean' ? body.hasSeenSafetyNotice : base.hasSeenSafetyNotice, updatedAt: new Date() }; await db.insert(wellnessProfile).values({ userId: user.id, ...values }).onConflictDoUpdate({ target: wellnessProfile.userId, set: values }); return NextResponse.json(values) }
